"""empty message

Revision ID: 4365a25e43ad
Revises: 
Create Date: 2018-06-24 19:15:50.709629

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4365a25e43ad'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('atividade',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cpf_cnpj', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clientes_cpf_cnpj'), 'clientes', ['cpf_cnpj'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('location', sa.String(length=64), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('member_since', sa.DateTime(), nullable=True),
    sa.Column('avatar_hash', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('funcionario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('matricula', sa.String(length=7), nullable=True),
    sa.Column('nome', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('senha', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('matricula')
    )
    op.create_table('projeto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.Text(), nullable=True),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('talks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('slides', sa.Text(), nullable=True),
    sa.Column('video', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('venue', sa.String(length=128), nullable=True),
    sa.Column('venue_url', sa.String(length=128), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('funcionario_projeto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('funcionario_id', sa.Integer(), nullable=True),
    sa.Column('projeto_id', sa.Integer(), nullable=True),
    sa.Column('cordenador', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['funcionario_id'], ['funcionario.id'], ),
    sa.ForeignKeyConstraint(['projeto_id'], ['projeto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lancamento_horas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_hora_inicio', sa.DateTime(), nullable=True),
    sa.Column('data_hora_fim', sa.DateTime(), nullable=True),
    sa.Column('atividade_id', sa.Integer(), nullable=True),
    sa.Column('projeto_id', sa.Integer(), nullable=True),
    sa.Column('funcionario_id', sa.Integer(), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['atividade_id'], ['atividade.id'], ),
    sa.ForeignKeyConstraint(['funcionario_id'], ['funcionario.id'], ),
    sa.ForeignKeyConstraint(['projeto_id'], ['projeto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ponto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_lancamento', sa.Date(), nullable=True),
    sa.Column('hora_inicio_1', sa.DateTime(), nullable=True),
    sa.Column('hora_fim_1', sa.DateTime(), nullable=True),
    sa.Column('hora_inicio_2', sa.DateTime(), nullable=True),
    sa.Column('hora_fim_2', sa.DateTime(), nullable=True),
    sa.Column('hora_inicio_3', sa.DateTime(), nullable=True),
    sa.Column('hora_fim_3', sa.DateTime(), nullable=True),
    sa.Column('funcionario_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['funcionario_id'], ['funcionario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ponto')
    op.drop_table('lancamento_horas')
    op.drop_table('funcionario_projeto')
    op.drop_table('talks')
    op.drop_table('projeto')
    op.drop_table('funcionario')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_clientes_cpf_cnpj'), table_name='clientes')
    op.drop_table('clientes')
    op.drop_table('atividade')
    # ### end Alembic commands ###
